try {
    const sum = x + y;
} catch (error) {
    console.log(`${error}`);
}
